services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
    image: mysql:latest
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    command: fastapi dev --host 0.0.0.0 --port 8080
    env_file:
      - .env
    volumes:
      - ./backend:/code/
      - static_volume:/static
      - media_volume:/media
    restart: always
    ports:
      - "$BACKEND_OUTER_PORT:$BACKEND_INNER_PORT"
  frontend:
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend/
      - static_volume:/static
      - media_volume:/media
    restart: always
    ports:
      - "$FRONTEND_OUTER_PORT:$FRONTEND_INNER_PORT"
volumes:
  static_volume:
  media_volume:
  mysql_volume: